language: java
jdk:
    - openjdk8
os:
    - linux
branches:
    except:
        - master
cache:
    directories:
        - $HOME/.gradle
before_script:
    - 'export TZ=Europe/Berlin'
script:
    - './gradlew init'
    - './gradlew -Dorg.gradle.project.ii.etfdev.quality.reports=true test jacocoTestReport'
before_install:
    - 'if [ -n "$CODACY_PROJECT_TOKEN" ]; then wget -O ~/codacy-coverage-reporter-assembly.jar https://repo.jenkins-ci.org/public/com/codacy/codacy-coverage-reporter/5.0.310/codacy-coverage-reporter-5.0.310-assembly.jar; fi'
after_success:
    - 'if [ -n "$CODACY_PROJECT_TOKEN" ]; then java -jar ~/codacy-coverage-reporter-assembly.jar report -l Java -r build/reports/jacoco/test/jacocoTestReport.xml; fi'
